import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Web3Provider } from "../assets/components/web3Context";
import { SidebarProvider } from "@/assets/components/SidebarContext";
import { ChatSidebarProvider } from "@/assets/components/chats/chatSiderbarContext";
import { ThemeProvider } from "next-themes";
import Kbar from "../assets/components/kbar";
import WagmiProviderComp from "../lib/wagmi-provider";
import { cookieToInitialState } from "wagmi";
import { config } from "@/lib/config";
import { headers } from 'next/headers'; // Import headers for server-side cookie access

import { SearchProvider } from "@/assets/components/SearchContext"; // Import SearchProvider
import "./globals.css";
// import ChatPage from "../assets/components/chatPage"; // Assuming ChatPage is not globally needed here
import KbarBlurWrapper from "@/assets/components/KbarBlurWrapper"; // Import the new wrapper

// Removed direct font constant declarations as GeistSans and GeistMono handle this

export const metadata: Metadata = {
  title: "GITFUND",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Correctly get cookie on the server side for Wagmi initial state
  const headersList = await headers();
  const initialState = cookieToInitialState(config, headersList?.get("cookie"));  return (
    <html lang="en" className={`dark`}>
      <body className={`bg-background text-foreground`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <Web3Provider>
              <SessionProvider>
                <SearchProvider>
                  <ChatSidebarProvider>
                    <Kbar />
                    <WagmiProviderComp initialState={initialState}>
                    <KbarBlurWrapper> {/* Wrap children with the new component */}
                      {children}
                    </KbarBlurWrapper>
                    </WagmiProviderComp>
                    
                  </ChatSidebarProvider>
                </SearchProvider>
              </SessionProvider>
            </Web3Provider>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
