
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SessionProvider } from 'next-auth/react';
import {Web3Provider} from "../assets/components/web3Context";
import { SidebarProvider } from '@/assets/components/SidebarContext';

import "./globals.css";
import ChatPage from "../assets/components/chatPage";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GITFUND",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`bg-background text-foreground`}
      >
        <SidebarProvider>
        <Web3Provider>
         <SessionProvider>
         
        {children}
        <div className="fixed right-10 bottom-10">
            <ChatPage/>
        </div>
        
        </SessionProvider>
        </Web3Provider>
        </SidebarProvider>
        
      </body>
    </html>
  );
}
